// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzwwcituvkxkqvbiavcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56d3djaXR1dmt4a3F2YmlhdmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTA2MTMsImV4cCI6MjA2MDI2NjYxM30.EXcog9_4GQ-cJVL8XbiJpBiAI2Uy-5hQ-yeMiZhdfgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);